name: Build and Push to ECR - Notas de Venta

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
          docker login --username AWS --password-stdin 975050307414.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t notas-venta:latest .

      - name: Tag Docker image
        run: |
          docker tag notas-venta:latest 975050307414.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/notas-venta:latest

      - name: Push to Amazon ECR
        run: |
          docker push 975050307414.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/notas-venta:latest
